### ISSUE TITLE
Mise à jour automatique des dépendances

### ISSUE THREAD

**Issue by nicoca-ine** [WoCha-FR/jeedom-ring#19]
Bonjour,
Est-il possible lors de la maj du plugin de lancer automatiquement la maj des dépendances (fait par d'autres plugins)? ça éviterait d'oublier et de chercher plusieurs jours après pourquoi jeedom ne gère plus l'alarme.
Tks

**Comment by WoCha-FR** [comment]
Implémenter depuis le PR #20

**Comment by nicoca-ine** [comment]
top merci !
