### ISSUE TITLE
Problem snapshot

### ISSUE THREAD

**Issue by jacques3629** [WoCha-FR/jeedom-ring#2]
Pas d'image dans le dossier de capture 

commande 
http://localhost:55123/snapshot/54e****5c735.png

/var/www/html/plugins/camera/data/records

le dossier est bien créé, mais aucune capture n'apparait 

tout le reste fonctionne bien

**Comment by WoCha-FR** [comment]
Bonsoir,

Cela est normal ou anormal, tout dépends de votre configuration.

Merci de me préciser les éléments suivants : 
- Modèles de caméra
- Type de fonctionnement (Toujours, mode Extérieur, Mode Domicile)
- Configuration de la (des) caméra(s) dans l'application RING (Clic sur la caméra - Paramètres de l'appareil - Capture d'instantanés)

Une fois ces éléments reçus, je pourrais plus facilement vous aider à trouver la solution à votre problème.

Bien Cordialement.

**Comment by jacques3629** [comment]
> Bonsoir,
> 
> Cela est normal ou anormal, tout dépends de votre configuration.
> 
> Merci de me préciser les éléments suivants :
> 
>     * Modèles de caméra
> 
>     * Type de fonctionnement (Toujours, mode Extérieur, Mode Domicile)
> 
>     * Configuration de la (des) caméra(s) dans l'application RING (Clic sur la caméra - Paramètres de l'appareil - Capture d'instantanés)
> 
> 
> Une fois ces éléments reçus, je pourrais plus facilement vous aider à trouver la solution à votre problème.
> 
> Bien Cordialement.

Paramètre spécifique

ring
doorbell 3
extérieur


Sur l'appli ring
capture d'instantanés cochée
note: la capture d'instantanés nécessite un abonnement
ring protect
cela signifie que le plugin ne peut fonctionner pour la capture sans un abonnement ?

Merci, cordialement

**Comment by jacques3629** [comment]
![Capture  ring](https://user-images.githubusercontent.com/127342238/223906250-bc24b394-4314-4d4a-a42c-d710de5ed28f.JPG)

**Comment by jacques3629** [comment]
Je comprends mieux maintenant 
il faut peut-être le rajouter dans la documentation ?

Je vais me rabattre sur une automatisation avec le chimie pro
bonne journée
