### ISSUE TITLE
Ring Intercom

### ISSUE THREAD

**Issue by naos44** [WoCha-FR/jeedom-ring#3]
Bonjour,

J'essaye d'utiliser votre plugin sur Jeedom avec un Ring Intercom, mais l'équipement n'est pas détecté.
J'ai essayé de rajouter le fichier intercom.js en adaptant le fichier sur le modèle de lock.js mais sans succès...

Est-il possible que vous rajoutiez le support de ce nouvel équipement Ring ?

Merci beaucoup

**Comment by WoCha-FR** [comment]
Bonsoir.

Je regarde si la librairie nodejs le supporte et comment il est intégré à le dans le plugin.

Je pousserais une beta du plugin pour test par vos soins car je ne possède pas cet équipement.

Bonne soirée.

**Comment by WoCha-FR** [comment]
Bonjour,
La librairie utilisée par le plugin à bien intégrée l'intercom.
Je fait le nécessaire au niveau du plugin pour l'ajouter. Cependant, cela risque d'être un peu long car il y aussi eu du changement dans le live stream et je doit donc aussi reporter cette modification dans le plugin.
Bonne journée.

**Comment by naos44** [comment]
Bonjour,

Merci beaucoup, je viens de tester la dernière version beta du plugin: l'interphone est bien détecté, et les infos semblent bien remonter.
Il manque juste l'action de déverrouillage (unlock) de l'interphone

Merci pour votre travail
Bonne journée

**Comment by WoCha-FR** [comment]
Bonjour.Il est sur un nouveau topic.Comme je n'ai pas d'intercom, pouvez vous réaliser ces étapes pour moi :Passer le log en mode débugRedémarrez le démonActionner le local unclock depuis l'app téléphoneM'envoyer le log.Merci.Le 14 mai 2023 12:13, naos44 ***@***.***> a écrit :
Bonjour,
Merci beaucoup, je viens de tester la dernière version beta du plugin: l'interphone est bien détecté, et les infos semblent bien remonter.
Il manque juste l'action de déverrouillage (unlock) de l'interphone
Merci pour votre travail
Bonne journée

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/WoCha-FR/jeedom-ring/issues/3#issuecomment-1546862837",
"url": "https://github.com/WoCha-FR/jeedom-ring/issues/3#issuecomment-1546862837",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by naos44** [comment]
Bonjour,
ci-joint les logs, il n'y a pas de log spécifique qui apparait dans mqttRing.txt quand je déverrouille depuis l'application

Merci
Bonne journée

[mqttRingd.txt](https://github.com/WoCha-FR/jeedom-ring/files/11480608/mqttRingd.txt)
[mqttRing.txt](https://github.com/WoCha-FR/jeedom-ring/files/11480609/mqttRing.txt)

**Comment by WoCha-FR** [comment]
Bonjour,
Bien reçu.
Je m'y met dès que possible !
Merci pour votre aide.

**Comment by WoCha-FR** [comment]
Bonjour,
J'ai pousser ce matin une version beta du support de l'intercom.
Vous devriez voir apparaitre l'état et deux actions.
Merci de me confirmer que celà fonctionne.

**Comment by naos44** [comment]
Bonjour,

Les actions n'apparaissent pas, ci-joint la capture des commandes, il n'y a plus non plus l'état _Ding_

![image](https://github.com/WoCha-FR/jeedom-ring/assets/131774373/49dbae6e-b7c9-4d53-a4e2-615e4ea83342)


Merci

**Comment by WoCha-FR** [comment]
Re,
J'ai pousser une nouvelle beta à 17h45 qui pour moi règle le problème.
Pour l'état ding, c'est surprenant car c'est bien pris sur les sonnettes et c'est le même payload. Pour ce point, je poursuit mes investigations.

**Comment by naos44** [comment]
Bonjour,

Il n'y a pas de changement de mon côté, les commandes actions ne sont pas crées. Je peux essayer de créer les commandes manuellement si vous me donnez les paramètres à renseigner.

Merci

**Comment by WoCha-FR** [comment]
Bonjour,

Merci de me confirmer les points suivants : 
- Avez vous bien la dernière version béta ?
- Avez vous bien redémarrer le démon ? La découverte se fait au lancement du démon.

Pour que je puisse avancer plus vite, il me serait très utile d'avoir votre log debug mqttRing

Merci.

**Comment by naos44** [comment]
Bonjour,

Je vous confirme les points, je supprime également l'équipement avant de faire les manip afin qu'un nouvel équipement soit créé
ci-joint le log debug demandé

Merci
[mqttRing.log](https://github.com/WoCha-FR/jeedom-ring/files/11612147/mqttRing.log)

**Comment by WoCha-FR** [comment]
Bonjour,
Nouvelle beta en ligne. 
J'ai simuler des trames MQTT depuis votre log et sur mon Jeedom de test, tout a fonctionné. (Même le ding)
Merci de confirmer que tout est OK pour vous.

**Comment by WoCha-FR** [comment]
>  Par ailleurs les infos ding, lock et status sont de type string et non binaire.

Chez moi il sont bien en binaire, comme dans votre capture d'écran.
Ils doivent être en binaire pour fonctionner avec Jeedom, mon plugin se chargeant de faire la conversion depuis la librairie qui elle est en string.

**Comment by naos44** [comment]
Je viens de tester "en réel" chez moi.
La commande d'unlock fonctionne, par contre un appel interphone ne change pas l'état du ding qui reste à 0 / OFF

**Comment by WoCha-FR** [comment]
Bonjour,
Une nouvelle fois il me faudrait les log du démon et du plugin.
Il se peut que Ring n'envoie pas le push donc la librairie ne le voit pas, donc le plugin n'affiche rien.
Merci à vous.

**Comment by naos44** [comment]
Bonjour,

Ci-joint les logs. L'appel interphone a été effectué vers 17h43-44

Merci
[mqttRing_ding.log](https://github.com/WoCha-FR/jeedom-ring/files/11624040/mqttRing_ding.log)
[mqttRingd_ding.log](https://github.com/WoCha-FR/jeedom-ring/files/11624041/mqttRingd_ding.log)

**Comment by WoCha-FR** [comment]
Re,
Dans le log du démon, je vois que la librairie ne reçoit pas le DING des serveurs RING.
Donc le plugin n'est pas en cause. 
Il est très fort probable que cela vienne d'un problème identifié sur la librairie que le plugin utilise : [tsightler/ring-mqtt#643](https://github.com/tsightler/ring-mqtt/issues/643)
Je pense que nous allons devoir attendre une nouvelle version qui prendras en charge les modifications opérées par RING sur ces notifications.

**Comment by WoCha-FR** [comment]
Bonjour,
Beta poussée avec une nouvelle version de la librairie RING qui corrige votre dernier problème.

**Comment by naos44** [comment]
Bonjour,

Merci, je vais tester ça ce soir et vous tiens au courant

Bonne journée

**Comment by naos44** [comment]
Bonjour,

La librairie s'est bien mise à jour. Mais le ding ne fonctionne toujours pas, rien dans les logs...

Merci

**Comment by WoCha-FR** [comment]
Bonjour,
Si vous ne recevez pas de notifications après la mise à niveau (Sonnette,...), vous devez supprimer toutes les instances ring-mqtt précédemment authentifiées du Ring Control Center.

![retrait_appareils](https://github.com/WoCha-FR/jeedom-ring/assets/117277377/3fec8cf3-ba3f-4a87-87fd-42e16227ab29)

Il vous faudras ensuite reconnecter le plugin comme lors de son installation.

**Comment by naos44** [comment]
Bonjour,
Je vous confirme que tout fonctionne correctement maintenant 😀
Merci beaucoup !

**Comment by WoCha-FR** [comment]
Bonjour,
C'est une bonne nouvelle !!
Bonne fin de Week-end.
