### ISSUE TITLE
Ring Video Doorbell 2

### ISSUE THREAD

**Issue by pctetra** [WoCha-FR/jeedom-ring#6]
Bonjour
j'utilise votre plugin depuis un mois et au début, j'avais bien le flux RTSP, rtsp://xxx.xx.x.xxx:8554/xxxxxxxxx_live
que je visualisais avec le plugin camera.
Je ne l'ai plus, tous le reste fonctionne bien, j'ai bien le topic qui remonte dans mqtt explorer avec motionn et ding status ok

Par contre dans les logs de mqttRing en mode debug j'ai ces deux lignes qui reviennent régulièrement, je n'ai pas l'impression que je les avais avant
0422|[2023-05-18 10:47:54]WARNING : [xxxxxxxxxxxxx] Type non géré camera
0422|[2023-05-18 10:47:54]WARNING : [xxxxxxxxxxxxx] Type non géré select

Merci pour votre travail

**Comment by WoCha-FR** [comment]
Bonsoir,
Pouvez vous me confirmer que vous avez bien un abonnement "ring protect" valide ?
Êtes vous bien à la dernière version du plugin en librairie 5.2.2 ?
Merci.

**Comment by pctetra** [comment]
Bonsoir
Je n'ai plus l'abonnement depuis le début de l'année, mais ce qui m'a fait penser qu'il y avait une anomalie est que j'ai eu le live stream pendant deux semaines après l'installation du plugin sans problème, donc j'ai supposé que l'abonnement n'était pas obligatoire...
J'ai bien la librairie 5.2.2, j'ai installé la version béta

**Comment by hgmorse** [comment]
Bonjour,

J'ai exactement le même problème avec une camera floodlight.
Tout marche, sauf la remonté du flux vidéo, qui jusqu'à la MAJ fonctionnait.
J'ai bien un abonnement actif ;-)

en debug j'ai noté ces lignes
[2023-05-24 11:29:42][DEBUG] : Commande event_select/attributes/recordingUrl inconnue dans l'equipement 30fdXXX66/camera/54XXXb
[2023-05-24 11:29:42][DEBUG] : Commande event_select/attributes/eventId inconnue dans l'equipement 30fdXXX66/camera/54XXXb

**Comment by WoCha-FR** [comment]
Bonjour,
Je confirme que le flux RTSP est absent et qu'il ne nécessite pas d'abonnement actif.
J'ai identifié le soucis et mis en ligne une version beta qui corrige le problème.
Il faut réinstaller les dépendances.
Merci de votre retour !

**Comment by pctetra** [comment]
Bonjour,
Super ! ça fonctionne
Merci beaucoup pour votre réactivité et pour le travail d'autant que votre plugin est gratuit !
Très bon week end

**Comment by WoCha-FR** [comment]
Bonjour,
Merci de retour.
Je fais encore quelques ajustements et je passe en stable.
Bon (long) WE à vous aussi.

**Comment by pctetra** [comment]
trop content de voir le livestream, en réactivant mon scenario, il semble que je n'ai plus la détection de mouvement motion et sonnette (ding), est ce que ça vous parait possible
