### ISSUE TITLE
suite doorbell 2

### ISSUE THREAD

**Issue by pctetra** [WoCha-FR/jeedom-ring#7]
trop content de voir le livestream, en réactivant mon scenario, il semble que je n'ai plus la détection de mouvement motion et sonnette (ding), est ce que ça vous parait possible
je confirme, en mode debug, je vois bien la ligne livestream mais après rien alors qu'il y une detection de sonnerie et une detection de mouvement.

**Comment by pctetra** [comment]
le livestream n'était pas activé quand j'ai fait l'essai de détection de mouvement et sonnerie
j'ai refait un essai de detection de mouvement sans initier de livestream, j'ai dans l'historique de la sonnette sur l'appli ring une detection de mouvement une detection à 17h46 et 17h51 mais rien ne remonte
Dans les logs  MqttRingd je voyais l'initialisation du livestream précédemment indiqué

**Comment by WoCha-FR** [comment]
Je ne vois pas, ici ça fonctionne.
J'ai corriger une erreur de typo dans la classe PHP tout à l'heure que j'ai poussé en beta à 17h45.
Essayez avec cette version pour voir si c'est bien l'origine du problème.

**Comment by pctetra** [comment]
j'ai refait une install propre de la beta avec un nouveau token, j'avais juste fait une mise à jour de la stable, j'ai retrouvé la detection de mouvement 
donc ça semble bon, 
Merci encore

**Comment by WoCha-FR** [comment]
Je n'ai pas poussé la stable. Si vous avez la stable, vous devriez avoir perdu le livestream.

**Comment by pctetra** [comment]
je n'ai pas été clair, j'avais gardé l'ancienne stable sur ma jeedom, celle qui ne fonctionnait pas, quand vous m'avez envoyé le message, je ne l'ai pas désinstallée, j'ai installé la beta à partir du market par dessus et mis à jour les dépendances pour garder le token, j'ai retrouvé le live stream mais pas la détection de mouvement.
Là j'ai désinstallé complètement le plugin tout effacé et je suis reparti de zéro avec la beta, tout semble fonctionner maintenant

**Comment by WoCha-FR** [comment]
Parfait !
Je considère que tout est OK mais je laisse le ticket ouvert si vous constatez un soucis dans les jours à venir.
Bon week-end

**Comment by pctetra** [comment]
Merci, je vous tiendrais au courant si problème
Bon week-end

**Comment by pctetra** [comment]
Bonjour
la détection de mouvement remonte bien, mais je n'ai pas un comportement comme initialement dans la version qui fonctionnait il y a quelques semaines : à l'époque, je pouvais m'envoyer un snapshot avec un scenario par email, là  le scenario se déclenche bien mais je n'ai rien.

_Voilà ce que j'ai relevé dans le log mqttRing à l'horaire de la détection de mouvement 11h26 :_

0210[2023-05-27 11:26:06]DEBUG : Commande motion/attributes/lastMotionTime inconnue dans l'equipement #LOC_ID/camera/#CAMERA_ID
0211|[2023-05-27 11:26:06]DEBUG : Commande motion/attributes/personDetected inconnue dans l'equipement #LOC_ID/camera/#CAMERA_ID
0212|[2023-05-27 11:26:06]DEBUG : Commande motion/attributes/motionDetectionEnabled inconnue dans l'equipement #LOC_ID/camera/#CAMERA_ID
0213|[2023-05-27 11:29:07]DEBUG : Commande motion/attributes/lastMotion inconnue dans l'equipement #LOC_ID/camera/#CAMERA_ID
0214|[2023-05-27 11:29:07]DEBUG : Commande motion/attributes/lastMotionTime inconnue dans l'equipement #LOC_ID/#CAMERA_ID
0215|[2023-05-27 11:29:07]DEBUG : Commande motion/attributes/personDetected inconnue dans l'equipement #LOC_ID/camera/#CAMERA_ID
0216|[2023-05-27 11:29:07]DEBUG : Commande motion/attributes/motionDetectionEnabled inconnue dans l'equipement #LOC_ID/camera/#CAMERA_ID

_Et dans le log mqttRingd à la même heure sauf que dans ce log l'horodatage semble être GMT par rapport au log mqttRing_

0095|2023-05-27T09:26:06.420Z ring-mqtt [Doorbell] Received motion push notification, expires in 180 seconds
0096|2023-05-27T09:26:06.421Z ring-mqtt [Doorbell] Motion snapshot needed but notification did not contain image UUID and battery cameras are unable to snapshot while recording
0097|2023-05-27T09:26:06.422Z ring-mqtt [Doorbell] ring/#LOC_ID/camera/#CAMERA_ID/motion/state ON

Bonne journée

**Comment by pctetra** [comment]
Bonjour
Ne cherchez pas pour rien si personne d'autre ne se plaint, peut-être une mauvaise install.
Comme j'avais un peu de temps ce week-end, j'ai installé docker sur ma jeedom et directement le container de tsightler/ring-mqtt, vous pouvez clore le ticket.
Merci et bonne journée

**Comment by WoCha-FR** [comment]
Bonjour,

J'arrive a reproduire le soucis de temps en temps.
Il arrive que lors de la réception de la notification de mouvement, il n'y ai pas de snapshot joint : 
`Motion snapshot needed but notification did not contain image UUID and battery cameras are unable to snapshot while recording`

Le plugin fonctionne avec votre container ring-mqtt ?

Bonne journée.

**Comment by pctetra** [comment]
Bonjour
Non plus vraiment, je me retrouve dans la situation décrite par le développeur tsightler il y a  quelques heures, ça a fonctionné, mais ça ne fonctionne plus : https://github.com/tsightler/ring-mqtt/issues/643

Bonne journée

**Comment by pctetra** [comment]
Bonjour
je ne sais pas si vous avez vu la 5.3.0 est publiée en stable apparemment : https://github.com/tsightler/ring-mqtt/blob/main/docs/CHANGELOG.md

Me concernant j'utilise depuis quelques jours la dev 5.3.0, je n'ai plus le problème de perte de remontées motion, j'ai par contre des soucis pour récupérer les snapshot mais ça vient peut-être de chez moi, je reçois des fichiers vides.
Bonne journée

**Comment by WoCha-FR** [comment]
Bonjour,
Beta poussée avec une nouvelle version de la librairie RING.
Concernant les snapshots, je fais une modification dans la librairie pour que ce soit compatible avec Jeedom.
Bonne journée.

**Comment by pctetra** [comment]
Bonjour
plugin réinstallé, ok pour motion detection et live stream 
Pour les snapshots je vais attendre, il y aura surement une mise à jour, pour l'instant l'url indiquée dans la doc ne fonctionne paspour moi, mais je n'avais déjà pas les snapshots dans la version installée dans docker
bonne journée

**Comment by WoCha-FR** [comment]
@PASCALFrFl 
Bonjour, merci de créer une nouvelle "issue" avec votre problème.
Mettez les logs du plugin RING en mode debug, redémarrer le démon et joignez les logs à cette nouvelle "issue".
A partir de là, je pourrais commencer à investiguer.

**Comment by PASCALFrFl** [comment]
Je n'arrive pas à faire demarrer le Demon, en fait je n'arrive pas à me connecter au mqtt via MQTT Manager.
Je viens de créer un tiquet à Jeedom car j'ai ça dans la fenetre du MQTT : 
per_listener_settings true

listener 1883
persistence false
allow_anonymous false
password_file /var/www/html/plugins/mqtt2/core/class/../../data/passwords

listener 8883
persistence false
password_file /var/www/html/plugins/mqtt2/core/class/../../data/passwords
allow_anonymous false
cafile /var/www/html/plugins/mqtt2/core/class/../../data/ssl/ca.crt
certfile /var/www/html/plugins/mqtt2/core/class/../../data/ssl/mosquitto.crt
keyfile /var/www/html/plugins/mqtt2/core/class/../../data/ssl/mosquitto.key
require_certificate true

**Comment by PASCALFrFl** [comment]
Jeedom a reconfiguré le mqtt manager. Le pb ne vient pas de là. La fenêtre d'indentification des ring est vide (impossible à se charger)...

**Comment by PASCALFrFl** [comment]
![image_2023-06-12_190137247](https://github.com/WoCha-FR/jeedom-ring/assets/6573735/8f6a2389-23e4-4c00-adfc-a36dc6fb3e05)
![Capture d’écran 2023-06-12 185828](https://github.com/WoCha-FR/jeedom-ring/assets/6573735/ad28b611-0e7a-4f0c-b0cd-7a1fb0cf364c)

**Comment by pctetra** [comment]
@WoCha-FR : Bonjour effectivement je n'avais pas bien lu la doc, il faut un abonnement, merci pour tout, pour ce qui me concerne vous pouvez clore ce sujet

@PASCALFrFl vous auriez du ouvrir un autre sujet comme l'a dit le développeur du plugin
malgré tout une indication : votre démon n'est pas lancé donc logique que n'ayez pas la fenêtre pour récupérer le token

**Comment by WoCha-FR** [comment]
@pctetra : bien reçu. Merci.

@PASCALFrFl : Sur la capture d'écran, dépendances RING non installées et donc le démon ne démarre pas et donc vous n'avez pas la page d'identification.

Bonne soirée !

**Comment by PASCALFrFl** [comment]
Grrrr
Les dépendances Ring ont été lancées et relancées ! le Denon ne sera actif en démarrage qu'une fois la configuration configurée !!!
Bon, si je me trompe dites moi exactement quoi faire !

**Comment by PASCALFrFl** [comment]
Alors comment faire démarrer le Demon ??? si j'ai déjà lancé de très nombreuses fois les dépendances ? J'ai mis en écoute le mqtt manager bien sur.

**Comment by PASCALFrFl** [comment]
+ echo '*******************Begin of package installation******************'
*******************Begin of package installation******************
+ touch /tmp/jeedom_install_in_progress_mqttRing
+ echo 1
+ echo 2
+ sudo chmod +x /var/www/html/core/class/../../plugins/mqttRing/resources/pre_install.sh
+ sudo /var/www/html/core/class/../../plugins/mqttRing/resources/pre_install.sh
+ echo 'Pre installation de l'\''installation/mise à jour des dépendances mqttRing'
Pre installation de l'installation/mise à jour des dépendances mqttRing
+ PROGRESS_FILE=/tmp/jeedom_install_in_progress_mqttRing
+ echo 5
+++ dirname /var/www/html/core/class/../../plugins/mqttRing/resources/pre_install.sh
++ cd /var/www/html/core/class/../../plugins/mqttRing/resources
++ pwd
+ BASEDIR=/var/www/html/plugins/mqttRing/resources
+ cd /var/www/html/plugins/mqttRing/resources
+ '[' -d /var/www/html/plugins/mqttRing/resources/ring-mqtt ']'
+ echo 7
+ echo 'Pre install finished'
Pre install finished
+ echo 3
+ sudo chmod +x /var/www/html/core/class/../../plugins/mqttRing/resources/post_install.sh
+ sudo /var/www/html/core/class/../../plugins/mqttRing/resources/post_install.sh
+ echo 'Post installation de l'\''installation/mise à jour des dépendances mqttRing'
Post installation de l'installation/mise à jour des dépendances mqttRing
+ PROGRESS_FILE=/tmp/jeedom_install_in_progress_mqttRing
+ echo 20
+++ dirname /var/www/html/core/class/../../plugins/mqttRing/resources/post_install.sh
++ cd /var/www/html/core/class/../../plugins/mqttRing/resources
++ pwd
+ BASEDIR=/var/www/html/plugins/mqttRing/resources
+ GORTC_VER=1.5.0
++ sudo dpkg --print-architecture
+ FIND_ARCH=arm64
+ case ${FIND_ARCH} in
+ GORTC_ARCH=arm64
+ curl -L -s -o /usr/local/bin/go2rtc https://github.com/AlexxIT/go2rtc/releases/download/v1.5.0/go2rtc_linux_arm64
+ chown www-data:www-data -R /usr/local/bin/go2rtc
+ chmod +x /usr/local/bin/go2rtc
+ cd /var/www/html/plugins/mqttRing/resources
+ source ../core/config/mqttRing.config.ini
+ echo 'Wanted Version: 5.3.0
'
Wanted Version: 5.3.0
+ echo 50
+ git clone -b $'v5.3.0
_Jeedom' --depth 1 https://github.com/WoCha-FR/ring-mqtt.git /var/www/html/plugins/mqttRing/resources/ring-mqtt
Cloning into '/var/www/html/plugins/mqttRing/resources/ring-mqtt'...
warning: Could not find remote branch v5.3.0?_Jeedom to clone.
fatal: Remote branch v5.3.0?_Jeedom not found in upstream origin
+ echo 55
+ cd /var/www/html/plugins/mqttRing/resources/ring-mqtt
/var/www/html/core/class/../../plugins/mqttRing/resources/post_install.sh: line 34: cd: /var/www/html/plugins/mqttRing/resources/ring-mqtt: No such file or directory
+ npm ci
npm ERR! code EUSAGE
npm ERR! 
npm ERR! The `npm ci` command can only install with an existing package-lock.json or
npm ERR! npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
npm ERR! later to generate a package-lock.json file, then try again.
npm ERR! 
npm ERR! Clean install a project
npm ERR! 
npm ERR! Usage:
npm ERR! npm ci
npm ERR! 
npm ERR! Options:
npm ERR! [-S|--save|--no-save|--save-prod|--save-dev|--save-optional|--save-peer|--save-bundle]
npm ERR! [-E|--save-exact] [-g|--global] [--global-style] [--legacy-bundling]
npm ERR! [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
npm ERR! [--strict-peer-deps] [--no-package-lock] [--foreground-scripts]
npm ERR! [--ignore-scripts] [--no-audit] [--no-bin-links] [--no-fund] [--dry-run]
npm ERR! [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
npm ERR! [-ws|--workspaces] [--include-workspace-root] [--install-links]
npm ERR! 
npm ERR! aliases: clean-install, ic, install-clean, isntall-clean
npm ERR! 
npm ERR! Run "npm help ci" for more info

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-06-12T21_00_36_601Z-debug-0.log
+ echo 90
+ '[' -f /var/www/html/plugins/mqttRing/resources/ring-state.json ']'
+ chown www-data:www-data -R /var/www/html/plugins/mqttRing/resources/ring-mqtt
chown: cannot access '/var/www/html/plugins/mqttRing/resources/ring-mqtt': No such file or directory
+ chmod +x /var/www/html/plugins/mqttRing/resources/ring-mqtt/scripts/start-stream.sh
chmod: cannot access '/var/www/html/plugins/mqttRing/resources/ring-mqtt/scripts/start-stream.sh': No such file or directory
+ echo 'Everything is successfully installed!'
Everything is successfully installed!
+ echo 'Post install finished'
Post install finished
+ echo 4
+ php /var/www/html/core/class/../php/jeecli.php plugin dependancy_end mqttRing
+ rm /tmp/jeedom_install_in_progress_mqttRing
+ echo '*******************End of package installation******************'
*******************End of package installation******************

**Comment by WoCha-FR** [comment]
Merci de répondre dans l'issue #8 que j'ai créée à votre place.
