### ISSUE TITLE
Pas d'accès à l'authentification RING

### ISSUE THREAD

**Issue by WoCha-FR** [WoCha-FR/jeedom-ring#8]
Sur jeedom, j’ai bien installé mqtt manager mais sur le plugin lié à mqtt ring, impossible d’accéder à l’identifcation, je tombe sur l’adresse de mon jeedom :55123 et cela reste bloqué là, je ne vois aucune page s’afficher et ne peux donc configurermon compte ring. Le pb c’est que je ne sais bidouiller dans les fichiers, donc je n’arrive pas à m’en sortir quand on me dit de rentrer en ligne de commande...
Merci de votre aide

_Originally posted by @PASCALFrFl in https://github.com/WoCha-FR/jeedom-ring/issues/7#issuecomment-1586143834_

**Comment by WoCha-FR** [comment]
@PASCALFrFl 
Sur votre capture d'écran je ne vois pas tout.
Le démon affiche le statut "dépendances non installées".
Merci de me joindre le log d'installation des dépendances du plugin RING que je comprenne s'il y à un soucis.
Merci de me confirmer que le plugin est bien à jour et en version stable.

**Comment by WoCha-FR** [comment]
>       npm ERR! The `npm ci` command can only install with an existing package-lock.json or

Bonjour,
Les dépendances ne s'installent pas correctement.
Je regarde comment recréer (et corriger) celà car je n'ai pas le soucis lors de mes tests.

**Comment by jacques3629** [comment]
Bonjour 

je crois que j'ai un problème similaire les dépendance ne s'installe pas 
erreur NPM ?


+ echo '*******************Begin of package installation******************'
*******************Begin of package installation******************
+ touch /tmp/jeedom_install_in_progress_mqttRing
+ echo 1
+ echo 2
+ sudo chmod +x /var/www/html/core/class/../../plugins/mqttRing/resources/pre_install.sh
+ sudo /var/www/html/core/class/../../plugins/mqttRing/resources/pre_install.sh
+ echo 'Pre installation de l'\''installation/mise à jour des dépendances mqttRing'
Pre installation de l'installation/mise à jour des dépendances mqttRing
+ PROGRESS_FILE=/tmp/jeedom_install_in_progress_mqttRing
+ echo 5
+++ dirname /var/www/html/core/class/../../plugins/mqttRing/resources/pre_install.sh
++ cd /var/www/html/core/class/../../plugins/mqttRing/resources
++ pwd
+ BASEDIR=/var/www/html/plugins/mqttRing/resources
+ cd /var/www/html/plugins/mqttRing/resources
+ '[' -d /var/www/html/plugins/mqttRing/resources/ring-mqtt ']'
+ echo 7
+ echo 'Pre install finished'
Pre install finished
+ echo 3
+ sudo chmod +x /var/www/html/core/class/../../plugins/mqttRing/resources/post_install.sh
+ sudo /var/www/html/core/class/../../plugins/mqttRing/resources/post_install.sh
+ echo 'Post installation de l'\''installation/mise à jour des dépendances mqttRing'
Post installation de l'installation/mise à jour des dépendances mqttRing
+ PROGRESS_FILE=/tmp/jeedom_install_in_progress_mqttRing
+ echo 20
+++ dirname /var/www/html/core/class/../../plugins/mqttRing/resources/post_install.sh
++ cd /var/www/html/core/class/../../plugins/mqttRing/resources
++ pwd
+ BASEDIR=/var/www/html/plugins/mqttRing/resources
+ GORTC_VER=1.5.0
++ sudo dpkg --print-architecture
+ FIND_ARCH=amd64
+ case ${FIND_ARCH} in
+ GORTC_ARCH=amd64
+ curl -L -s -o /usr/local/bin/go2rtc https://github.com/AlexxIT/go2rtc/releases/download/v1.5.0/go2rtc_linux_amd64
+ chown www-data:www-data -R /usr/local/bin/go2rtc
+ chmod +x /usr/local/bin/go2rtc
+ cd /var/www/html/plugins/mqttRing/resources
+ source ../core/config/mqttRing.config.ini
+ echo 'Wanted Version: 5.3.0
'
Wanted Version: 5.3.0
+ echo 50
+ git clone -b $'v5.3.0
_Jeedom' --depth 1 https://github.com/WoCha-FR/ring-mqtt.git /var/www/html/plugins/mqttRing/resources/ring-mqtt
Cloning into '/var/www/html/plugins/mqttRing/resources/ring-mqtt'...
warning: Could not find remote branch v5.3.0?_Jeedom to clone.
fatal: Remote branch v5.3.0?_Jeedom not found in upstream origin
+ echo 55
+ cd /var/www/html/plugins/mqttRing/resources/ring-mqtt
/var/www/html/core/class/../../plugins/mqttRing/resources/post_install.sh: line 34: cd: /var/www/html/plugins/mqttRing/resources/ring-mqtt: No such file or directory
+ npm ci
npm ERR! code EUSAGE
npm ERR!
npm ERR! The `npm ci` command can only install with an existing package-lock.json or
npm ERR! npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
npm ERR! later to generate a package-lock.json file, then try again.
npm ERR!
npm ERR! Clean install a project
npm ERR!
npm ERR! Usage:
npm ERR! npm ci
npm ERR!
npm ERR! Options:
npm ERR! [-S|--save|--no-save|--save-prod|--save-dev|--save-optional|--save-peer|--save-bundle]
npm ERR! [-E|--save-exact] [-g|--global] [--global-style] [--legacy-bundling]
npm ERR! [--omit  [--omit  ...]]
npm ERR! [--strict-peer-deps] [--no-package-lock] [--foreground-scripts]
npm ERR! [--ignore-scripts] [--no-audit] [--no-bin-links] [--no-fund] [--dry-run]
npm ERR! [-w|--workspace  [-w|--workspace  ...]]
npm ERR! [-ws|--workspaces] [--include-workspace-root] [--install-links]
npm ERR!
npm ERR! aliases: clean-install, ic, install-clean, isntall-clean
npm ERR!
npm ERR! Run "npm help ci" for more info
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-06-14T01_40_02_867Z-debug-0.log
+ echo 90
+ '[' -f /var/www/html/plugins/mqttRing/resources/ring-state.json ']'
+ chown www-data:www-data -R /var/www/html/plugins/mqttRing/resources/ring-mqtt
chown: cannot access '/var/www/html/plugins/mqttRing/resources/ring-mqtt': No such file or directory
+ chmod +x /var/www/html/plugins/mqttRing/resources/ring-mqtt/scripts/start-stream.sh
chmod: cannot access '/var/www/html/plugins/mqttRing/resources/ring-mqtt/scripts/start-stream.sh': No such file or directory
+ echo 'Everything is successfully installed!'
Everything is successfully installed!
+ echo 'Post install finished'
Post install finished
+ echo 4
+ php /var/www/html/core/class/../php/jeecli.php plugin dependancy_end mqttRing
+ rm /tmp/jeedom_install_in_progress_mqttRing
+ echo '*******************End of package installation******************'
*******************End of package installation******************

**Comment by WoCha-FR** [comment]
@jacques3629 
@PASCALFrFl

Bonjour,
Je viens de pousser une nouvelle stable qui corrige le problème que vous rencontrez.
Je ne sais pourquoi, le fichier de configuration est au format DOS et donc il y à un retour de ligne à la fin de la variable des dépendances, et donc elle ne s'installe pas.

**Comment by PASCALFrFl** [comment]
Yes, ça marche. Un Grand Merci :)

**Comment by jacques3629** [comment]
Merci beaucoup tout fonctionne à nouveau

**Comment by WoCha-FR** [comment]
@PASCALFrFl 
@jacques3629 

Merci pour ce retour, je clos l'Issue.
N'hésitez pas de noter le plugin dans le market Jeedom ;)
