### ISSUE TITLE
live stream version stable

### ISSUE THREAD

**Issue by pctetra** [WoCha-FR/jeedom-ring#9]
Bonjour
Vous confirmez que le live stream ne fonctionne que sur la version beta
Du moins avec la Ring Video Doorbell 2
J'ai réinstallé la version stable suite à modification de mon installation et je n'avais pas le live stream

C'est ok depuis que j'ai remis la beta.

Bonne journée

**Comment by WoCha-FR** [comment]
Bonjour,
Je confirme.
Une nouvelle stable est prévu prochainement, je modifie pas mal de choses en ce moment.
Bon Week-End
